### ISSUE TITLE
Missing GPG Key

### ISSUE THREAD

**Issue by haumanto** [matteocorti/check_updates#51] opened 2022-06-30 13:59 UTC
When I tried to run it via nrpe, it gives "CHECK_UPDATES UNKNOWN - Missing GPG key, run "dnf check-update" manually" but when I run it via cli it gives result

/usr/lib64/nagios/plugins/check_updates
CHECK_UPDATES CRITICAL - 7 non-security updates available | total_updates=7;0;0 security_updates=0;0;0
bpftool.x86_64
kernel.x86_64
kernel-core.x86_64
kernel-modules.x86_64
kernel-tools.x86_64
kernel-tools-libs.x86_64
python3-perf.x86_64

Please help

**Comment by matteocorti** [comment] 2022-06-30 14:00
Duplicate of #44

**Closed by matteocorti** 2022-06-30 14:00 UTC
Labels: bug, duplicate
